### ISSUE TITLE
get_predicted(): features and caveats

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/insight#315]
Here's a list of all features / issues etc., to have a global view and avoid opening multiple issues.

- [ ] 1. API Design (https://github.com/easystats/insight/issues/310)
- [ ] 2. Correct intervals for lme4 (https://github.com/easystats/insight/issues/298)
- [ ] 3. Prediction intervals for Bayesian GLMs (https://github.com/easystats/insight/issues/310#issuecomment-792276163)
- [ ] 4. Fix for "log()" terms in formula (https://github.com/easystats/insight/issues/314)
- [ ] 5. Multiple CIs (https://github.com/easystats/insight/issues/313)
- [ ] 6. Support prediction intervals for GAMs 
  - https://fromthebottomoftheheap.net/2016/12/15/simultaneous-interval-revisited/
  - https://github.com/gavinsimpson/gratia/blob/master/R/confint-methods.R
  - https://github.com/gavinsimpson/gratia/blob/master/R/posterior-samples.R
- [ ] 7. Support for other models

**Comment by IndrajeetPatil** [comment]
Do you think this function should ultimately be assigned to its own package? 

A package like `prediction`, `predicted`, etc. (not sure which names are available on `CRAN`).

I would also recommend having an alias for this function called `model_predictions`.

This would mean the ecosystem would have a consistent function naming schemas and also mirror functions for `broom` functions:

```r
broom::tidy     <->  parameters::model_parameters
broom::glance   <->  performance::model_performance
broom::augment  <->  prediction::model_prediction
```

What do you think? cc @strengejacke, @mattansb

**Comment by strengejacke** [comment]
Well, we have the modelbased package. I think @DominiqueMakowski just wanted to put the workhorse into insight, and then the "visible" user function will be in modelbased.

**Comment by IndrajeetPatil** [comment]
> the "visible" user function will be in modelbased

I see, gotcha! 

What do you think about calling this function `model_prediction`?

**Comment by DominiqueMakowski** [comment]
Yes correct, the idea was to have the heavy lifting done at the insight level, mostly it is useful elsewhere (performance indices for intance or such). Then, modelbased will be a user-facing package focusing mostly on visualization of models (including visualization of links, contrasts, marginal means etc). I plan to add nice vignettes to modelbased dicsussing a model-based approach to stats, how to make inference and derive indices from models etc. 

the function are currently named `estimate_link` and `estimate_response` but given the new API of get_predicted I might change to something like `estimate_relationship()` and `estimate_response()` or something like this

**Comment by strengejacke** [comment]
But we would still use both emmeans and predict, right?

**Comment by DominiqueMakowski** [comment]
yes yes for `estimate_means` and `estimate_contrasts` as the internals of that are definitly beyond us

**Comment by strengejacke** [comment]
Not as option for estimate_response? See https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html

**Comment by DominiqueMakowski** [comment]
mmh we'll see, but I feel like for modelbased we could really merge your and indra's experience with model visualization to make something really neat and powerful.

**Comment by strengejacke** [comment]
Support for other models, here I list some special cases:

- logistf: https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_logistf.R
- bamlss: https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_bamlss.R
- clm (and other ordinal / cumulative link models): https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_clm.R (these are great, you have to deal with the different outcome levels)
- lrm, multinom, ols, polr, ...: https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_lrm.R (different names for "type" argument)
- VGAM: https://github.com/strengejacke/ggeffects/blob/master/R/get_predictions_vglm.R (different name for "predict"?)

**Comment by strengejacke** [comment]
"clmm" is only supported by emmeans, has not predict.

**Comment by mattansb** [comment]
I've added prediction intervals for Binomial and Poisson models:

``` r
library(insight)
library(magrittr)

glm(am ~ cyl + mpg + hp, data = mtcars,
    family = binomial()) %>% 
  get_predicted(predict = "prediction") %>% 
  as.data.frame() %>% head() %>% zapsmall()
#>                   Predicted CI_low CI_high
#> Mazda RX4         0.1762632      0       1
#> Mazda RX4 Wag     0.1762632      0       1
#> Datsun 710        0.6499998      0       1
#> Hornet 4 Drive    0.2489592      0       1
#> Hornet Sportabout 0.2268359      0       1
#> Valiant           0.0064952      0       0

glm(gear ~ ., data = mtcars,
    family = poisson()) %>% 
  get_predicted(predict = "prediction") %>% 
  as.data.frame() %>% head() %>% zapsmall()
#>                   Predicted CI_low CI_high
#> Mazda RX4          4.266709      1       9
#> Mazda RX4 Wag      4.192287      1       9
#> Datsun 710         4.031290      1       8
#> Hornet 4 Drive     3.043687      0       7
#> Hornet Sportabout  2.967043      0       7
#> Valiant            2.890863      0       7
```

<sup>Created on 2021-03-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The Gaussian PIs still work as they use to (:

As I noted somewhere prior, each family has its own PI method, so adding *each* these analytical solutions is somewhat tedious... It might be easier to simulate population values and get the 95% ETI from there instead.

----

Also, these columns should really be `PI_low` and `PI_high`...

**Comment by DominiqueMakowski** [comment]
@mattansb I hope you found the code clear and logical :) 

One thing to make sure of:

Following your comments, currently the PIs for Bayesian models are obtained via their bespoke function:

https://github.com/easystats/insight/blob/da33355faf3868616736499f793377e88e2d8d30/R/get_predicted_ci.R#L115

instead of manually computing them from the draws. But does their function does something else than that? Or is it unnecessarily re-sampling draws from the posterior? (note that the iterations were obtained via posterior_predict).

**Comment by mattansb** [comment]
> instead of manually computing them from the draws. But does their function does something else than that?

Nope - that's exactly what it does:

https://github.com/stan-dev/rstanarm/blob/dee0a2d45bf42b2df791072041151b753edd6af9/R/predictive_interval.R#L82-L91

**Comment by DominiqueMakowski** [comment]
thanks for addressing my source-code-checking laziness 😁

**Comment by mattansb** [comment]
>  @strengejacke @mattansb is it possible to get PIs for GAMs? Can we use the same method that for lm/glms?

The code I wrote should also work with GLM GAMs. Is there any reason the same won't apply for gaussian models?

**Comment by strengejacke** [comment]
@DominiqueMakowski Currently, some methods like `get_predicted.glmmTMB()` directly check the `predict` argument, while others like `get_predicted.lmerMod()` call `.get_predicted_args()` to check the input. This leads to the situation that we have methods that have `predict = c("expectation", "link", "prediction", "response", "relation")` in their usage, while others just have `predict = "expectation"`. Can this be harmonized?

**Comment by strengejacke** [comment]
See https://github.com/easystats/insight/commit/4aa8e44bb22980857a4ec24e47a984b5367da4e2

**Comment by bwiernik** [comment]
> Prediction intervals for glmmTMB: Also, why are confidence intervals so different in respect to lme4 (could be related to issue above)

Note that by default, glmmTMB uses Wald CIs on fixed effects/log variance components, whereas lme4 uses profile likelihood CIs on fixed effects/variance components
